### ISSUE TITLE
Feature request: Reference a `requirements.txt` file from `application.yaml`

### ISSUE THREAD

**Issue by rudolfbyker** [AutoActuary/app-builder#38]
It would be very useful for me to move the Python requirements from `application.yaml` to a `requirements.txt` file. Use case: I want to run something like Mypy in CI, and I want to install just the Python dependencies from `application.yaml` without doing a full `app-builder -d`.

**Comment by rudolfbyker** [comment]
I could use `yq` to query the requirements, but the `application.yaml` format is a bit cumbersome: The python version is specified in a key, so the key contains ` ` and `.` characters.

Another spin-off feature request (breaking change) would be to redesign the `application.yaml` structure a bit:

```yaml
Dependencies:
  python:
    version: 3.11.1
    pip: 23.1.2
    requirements:
      - foo==1.2.3
      - bar==2.*
    requirements_files:
      - requirements.txt
      - some/other/requirements.txt
```
