### ISSUE TITLE
Installer file mapping

### ISSUE THREAD

**Issue by heetbeet** [AutoActuary/app-builder#6]
I don't like the current file mapping setup:
![image](https://user-images.githubusercontent.com/4103775/130742043-9a8fc1c7-4274-4765-b6a3-ce1061280610.png)

1. Don't allow renaming (if you _need_ to rename, rather write a `pre-build` and `post-build` script to do that type of ugly stuff. I think forcing a 1:1 relationship between the dev and installed app is much better.
2. Allow _include_ and _exclude_ filters (in sequential order, i.e. where last filter takes preference over previous ones)
3. Allow full glob descriptions including recursive globbing patterns (like that `**` thing)

Something easy like
```
data:
   include: 
       [bin, cli, app_builder]
   exclude:
       - bin/bootstrap-python.bat
       - bin/functions.bat
       - bin/post-dependencies.cmd
       - bin/pre-build.cmd
```

**Comment by heetbeet** [comment]
I have implemented:

```
data:
   include: 
       [bin, cli, app_builder]
   exclude:
       - bin/bootstrap-python.bat
       - bin/functions.bat
       - bin/post-dependencies.cmd
       - bin/pre-build.cmd
    rename:
       - [bin/pre-build.cmd, other-location/new-name.cmd]
```

Will add to v0.2.0
